apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ajthakurdepday5
  name: ajthakurdepday5
  namespace: ajthakur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ajthakurdepday5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ajthakurdepday5
    spec:
      containers:
      - image: ajay8naruto/eyappday5:v1
        name: eyappday5
        imagePullPolicy: Always
        resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ajthakurdepsvc1
  name: ajthakurdepsvc1
  namespace: ajthakur
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ajthakurdepday5
  type: NodePort
status:
  loadBalancer: {}
